/**
 * Test stub for the `astro:env/server` virtual module.
 * The real module is generated by Astro from the env schema in astro.config.mjs;
 * it does not exist outside an Astro build, so tests resolve to these fixed values
 * (wired via vite.config.ts `test.alias` for Vitest and tsconfig `paths` for bun).
 */
export const STRAPI_URL = 'http://strapi.test';
export const STRAPI_TOKEN = 'test-token';
